HW4 scripts moved to config-scripts, added packer build files, added …
Otus-DevOps-2022-05/hokum83_infra pull request #4
Opened 2022-07-05 21:02 UTC by hokum83

…yc compute deploy script based on packer image

# Выполнено ДЗ №5

 - [x] Основное ДЗ
 - [x] Задание со *

## В процессе сделано:
- настроены билдеры для файла создания образа packer в yc packer/ubuntu16.json
- настроены провиженеры для файла создания образа packer в yc packer/ubuntu16.json (2 скрипта установки монго и руби)
- некоторые параметры вынесены в файл переменных (примеры в packer/files/variables.json.examples)
- создан скрипт установки всех зависимостей, приложения и запуска приложения через юнит systemd - packer/scripts/prepare.sh
- создан файл для создания образа со всеми зависимостями и установленным приложением - packer/immutable.json
- создан скрипт развертывания вм из созданного пакером образа - config-scripts/create-reddit-vm.sh
- выполнено тестовое развертывание образа и вм на его основе

## Как запустить проект:
 - Запустить команду 'packer build -var-file=files/variables.json immutable.json' в директории 'packer'
 - Запустить скрипт 'create-reddit-vm.sh' в директории 'config-scripts'

## Как проверить работоспособность:
 - перейти по ссылке http://внешнийip:9292

## PR checklist
 - [x] Выставил label с номером домашнего задания
 - [x] Выставил label с темой домашнего задания

2022-07-05 21:09 UTC, hokum83 commented
Тест ругается на пример путей до ключа, который находится вне репозитория. Нужно в репу запихать пустой файл для прохождения теста?

2022-07-06 08:01 UTC, mrgreyves requested changes
Здравствуйте!)
Да, все верно
Нужно добавить ключик с фейковыми данными
Выглядит как приключение на 15 минут =)

2022-07-07 09:05 UTC, mrgreyves approved these changes
Здравствуйте!)
Апрув!=)

2022-07-07 09:10 UTC, hokum83 commented
> Здравствуйте!) Апрув!=)

Добрый день, спасибо!

2022-07-07 09:10 UTC, merged